# Generated by Django 3.1 on 2020-10-12 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member',
            field=models.ManyToManyField(blank=True, default=None, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
    ]
