# Generated by Django 3.1 on 2020-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=16, verbose_name='发布人')),
                ('title', models.TextField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=800, verbose_name='内容')),
                ('require_upload', models.BooleanField(default=False, verbose_name='需要上传')),
                ('issue_datetime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('edit_datetime', models.DateTimeField(auto_now=True, verbose_name='最新修改时间')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='截止时间')),
                ('url_address', models.TextField(blank=True, max_length=200, verbose_name='转发路径')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.IntegerField(verbose_name='通知id')),
                ('reader', models.CharField(max_length=16, verbose_name='阅读人')),
                ('image', models.ImageField(blank=True, upload_to='image', verbose_name='图片')),
                ('read_datetime', models.DateTimeField(auto_now=True, verbose_name='确认时间')),
                ('read_status', models.CharField(max_length=10, verbose_name='阅读状态')),
            ],
            options={
                'verbose_name': '公告确认明细',
                'verbose_name_plural': '公告确认明细',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.IntegerField(verbose_name='通知id')),
                ('sender', models.CharField(max_length=16, verbose_name='发送人')),
                ('sent_datetime', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('comment', models.TextField(max_length=100, verbose_name='内容')),
                ('reply_to', models.IntegerField(null=True, verbose_name='回复id')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
            },
        ),
    ]
