# Generated by Django 3.1 on 2020-10-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='to_group',
            field=models.ManyToManyField(blank=True, related_name='to_group', to='team.Team', verbose_name='接收组'),
        ),
    ]
