# Generated by Django 3.1 on 2020-10-11 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcement', '0002_announcement_to_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='to_people',
            field=models.ManyToManyField(blank=True, related_name='to_people', to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
