# Generated by Django 3.1 on 2020-10-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_to_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='team_id',
            field=models.CharField(max_length=32, null=True, verbose_name='团队id'),
        ),
        migrations.AddField(
            model_name='announcementrecord',
            name='team_id',
            field=models.CharField(max_length=32, null=True, verbose_name='团队id'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='team_id',
            field=models.CharField(max_length=32, null=True, verbose_name='团队id'),
        ),
    ]
